### ISSUE TITLE
Dependencies with resolved CQs are still shown as restricted

### ISSUE THREAD

**Issue by olexii4** [eclipse/dash-licenses#20]
Dependencies with resolved CQs are still shown as restricted.

For example, we already have CQs for the following runtime dependencies:
[attr-accept@1.1.3(CQ22348)](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22348)
[dom-helpers@3.4.0(CQ22349)](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22349)
[file-selector@0.1.12(CQ22350)](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22350)
[json5@1.0.1(CQ22351)](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22351)
[nan@2.14.1(CQ22352)](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22352)
[popper.js@1.16.1(CQ22353)](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22353)
[prop-types-extra@1.1.1(CQ22354)](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22354)
[react-dropzone@9.0.0(CQ22355)](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22355)
[vscode-languageclient@6.1.3(CQ22358)](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22358)
[warning@4.0.3(CQ22359)](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22359)

They were resolved a week ago.

The next run of dash-license shows that dependencies are still rejected:

```
…
npm/npmjs/-/attr-accept/1.1.3, unknown, restricted, none
…
npm/npmjs/-/dom-helpers/3.4.0, unknown, restricted, none
…
npm/npmjs/-/file-selector/0.1.12, unknown, restricted, none
…
npm/npmjs/-/json5/1.0.1, unknown, restricted, none
…
npm/npmjs/-/nan/2.14.1, unknown, restricted, none
…
npm/npmjs/-/popper.js/1.16.1, unknown, restricted, none
…
npm/npmjs/-/prop-types-extra/1.1.1, unknown, restricted, none
…
npm/npmjs/-/react-dropzone/9.0.0, unknown, restricted, none
…
npm/npmjs/-/vscode-languageclient/6.1.3, unknown, restricted, none
…
npm/npmjs/-/warning/4.0.3, unknown, restricted, none
…
```

### dash-licenses commit
b90756084cac437443b48f1d48edab6e991f2697

### Steps to reproduce:

1. Clone and build dash-licenses.
```
$ git clone https://github.com/eclipse/dash-licenses.git
$ cd dash-licenses && mvn clean install
$ cd yarn && yarn install && cd -
```
2. Download the target yarn.lock file.
```
$ wget https://raw.githubusercontent.com/che-incubator/che-dashboard-next/master/yarn.lock
```
3. Run dash-licenses
```
$ node yarn/index.js | java -jar target/org.eclipse.dash.licenses-0.0.1-SNAPSHOT.jar -
```
The new file  DEPENDENCIES will be created

**Comment by waynebeaton** [comment]
There was a bug in the script that pulls the NPM id from the CQ description. I've fixed it.

Try it now.

**Comment by olexii4** [comment]
@waynebeaton It works much better now, but we still have some missings.

For example: 'npm/npmjs/@types/axios/0.14.0'
```
...
npm/npmjs/-/detect-node/2.0.4, unknown, restricted, none
npm/npmjs/@types/axios/0.14.0, unknown, restricted, none
npm/npmjs/-/remark-parse/6.0.3, unknown, restricted, none
...
```

But we have https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22386
And 'npm/npmjs/@types/axios/0.14.0' was included

**Comment by waynebeaton** [comment]
I haven't quite figured out how to deal with "works with" dependencies. See #13.

**Comment by olexii4** [comment]
Thanks
